### ISSUE TITLE
[feature request] Opción de privacidad extendida

### ISSUE THREAD

**Issue by LuisMitaHL** [r00thouse/laotrared-admin#5]
Cuando alguien desea agregar un nodo (y recurriendo al formulario de nuevos nodos para tal efecto) seria una buena idea agregar un checkbox "Privacidad extendida" para que el usuario indique que el lugar donde ubica su nodo en el mapa es su casa o es algún lugar privado, y que no desea que la ubicación exacta salga en los mapas globales y/o públicos.

Podría implementarse agregando una opción extended_privacy en la tabla de la DB (boolean) pero guardando la misma coordenada exacta en la DB (ya que necesitamos los datos bien exactos para poder calcular luego probabilidad de enlaces y densidad de nodos).

Luego, el script encargado de mostrar mapas públicos, si detecta este atributo, le dé al frontend coordenadas menos exactas (+-30metros? suprimiendo un decimal?) y que dibuje un círculo indicando el posible rango estimado, en vez de la ubicación exacta.

**Comment by donkeysharp** [comment]
Cuando se registra o actualiza un nodo se adiciona una posición falsa en un radio máximo de aproximadamente 30 metros. La posición original se mantiene para el que mantiene el nodo.

https://github.com/r00thouse/laotrared-admin/commit/dd2608210092324094d7279dd591c054a98f63ca
